### ISSUE TITLE
Sample utterances do not support adjacent slots

### ISSUE THREAD

**Issue by lukelafountaine** [bespoken/virtual-core#11]
Phrases do not correctly match sample utterances that contain adjacent slots. 

For example, if a sample utterance for my intent is:
```
"{slotA} {slotB}"
```

I would expect:
```
"a b"
```
to match that intent. Currently, it does not. 

Is there any plan to support adjacent slots?

**Comment by jperata** [comment]
Hi @lukelafountaine , because slots can be multiple words there is no way to differentiate for us in the emulator. We only use regular expressions instead of AI as Alexa does. In your scenario "a b" might be a fit for just slotA, or just SlotB or A and B as you indicated.
In this scenarios we suggest you to use your intent directly specifying the intent using the intend methods on our implementations.

**Comment by jthomerson** [comment]
@jperata is there no way to build the regular expressions to include all the possible combinations of words? Obviously that could lead to a large matrix of combinations, but maybe with some limit on the combinations that it's allowed?

Example:

 * slotA type has these words:
   * play
   * read
   * explain
 * slotB type has these words:
   * life
   * the universe
   * everything

Regex is something akin to `(play|read|explain) (life|the universe|everything)`?

**Comment by jkelvie** [comment]
Hi @jthomerson - though that is perhaps feasible, keep in mind the limitations of this unit-testing framework. It is NOT a stand-in for the ASR/NLU performed by Alexa or Google Assistant. The regexes we use for matching utterances to intents are really just for convenience - they do not actually confirm at all how well your interaction model is working, or whether it is all configured correctly. This is because we completely bypass Alexa and Google Assistant, instead generating JSON payloads similar to what they create from whole cloth.

So, we do basic utterance resolution, and for more complex cases, we recommend passing the intent and setting the slots directly.

Example:
```
virtualAlexa.intend("MyIntent", { "SlotA": "ValueA" });
```

Hope that makes sense! If you are wanting to confirm the behavior of the ASR and NLU, I recommend taking a look at our [end-to-end testing](https://read.bespoken.io/end-to-end/getting-started) - that interacts with the real Alexa and Google Assistant. It is slower, but provides testing that very closely imitates a "real" person interacting with a device.

**Comment by jthomerson** [comment]
Thanks @jkelvie. That makes a lot of sense and I think helps guide us towards where we need to be with our unit testing for this. Thanks!
